# -*- coding: utf-8 -*-
"""3_funcoes_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbwD-czP0HccNmCBuUn1GHueVXYRTZgB

# Funções

Métodos são blocos de códigos reutilizáveis que realizam tarefas específicas dentro de um programa. Em Python, definimos funções usando a palavra-chave *def*, seguida pelo nome da função, a lista formal de parâmetros entre parêntesis, e, finalizando a assinatura do método com dois pontos (:). É importante lembrar que todas as instruções após a assinatura do método e que formam o corpo da função, devem ser identadas para funcionamento correto do código.

```python
def soma(a, b):
    '''Retorna a soma de dois números inteiros'''
    return a + b;


# Exemplo de uso da função
resultado_soma = soma(12, 15) 
print(resultado_soma) # Saída: 27

```

Você deve ter notado o comentário logo após a assinatura do método; este tipo de comentário é o que chamamos de *docstring*, e serve para documentarmos as funções para posteriormente, gerarmos automaticamente com auxílio de ferramentas, uma documentação online ou impressa do seu programa. Por isso, comente sempre seu código e escreva-o de maneira mais clara possível para que outras pessoas consigam ler e compreender facilmente o que seu código faz.

## Declaração de Argumentos

Existem 3 formas diferentes, que podem ser combinadas entre si, para definirmos funções com número variável de argumentos, são elas:

**1. Valores Padrão de Argumento**: declaramos um valor padrão para um ou mais argumentos no seguinte formato: *"arg = value"*; de tal forma que damos a opção de não especificar valores para tais argumentos e usarmos os valores padrão definidos.

```python
def exibir_mensagem(mensagem, cortar_apos = 4):
    print(message[:cortar_apos]

# Exemplo de uso da função
exibir_mensagem("mensagem")     # Saída: mens
exibir_mensagem("mensagem", 6)  # Saída: mensag
```

**2. Argumentos por Palavras-Chave**: semelhante a técnica anterior, argumentos por palavra-chave nós declaramos os argumentos no formato *"arg = value"*, lembrando que em uma chamada de função as variáveis passadas como parâmetro devem seguir a mesma ordem dos argumentos na assinatura do método.

```python
def desenha_retangulo(x, y, width = 800, height = 600):
    # Instruções
    
# Exemplo de uso da função
desenha_retangulo(0, 0)                               # Argumento por posição usando valores padrão do restante 
desenha_retangulo(0, 0, width = 1280)                 # Argumento com uma palavra-chave
desenha_retangulo(0, 0, width = 1280, height = 1024)  # Argumento com duas palavras-chave
desenha_retangulo()                                   # Erro: required argument missing
desenha_retangulo(color = "#CCCCCC")                  # Erro: argumento por palavra-chave desconhecido
desenha_retangulo(0, 0, x = 200, y = 300)             # Erro: valores duplicados par ao mesmo argumento

```

**3. Listas de Argumentos Arbitrários**: o Python permite você criar listas de argumentos com tamanho variável, de forma que toda vez que você chamar a função você possa especificar qualquer quantidade de argumentos que serão empacotados em uma variável do tipo tupla.

```python
# O último argumento é marcado com uma asterisco 
# para indicar que após os dois primeiros parâmetros
# qualquer dado enviado para a função será empacotado em uma tupla.
def nome_funcao(primeiro_arg, segundo_arg, *restante):
    # Instruções
    
```

## Passagem por Valor ou Por Referência?

Em Python, objetos passados como argumentos para as funções são passados por *referência*, ou seja, não é feita uma cópia deles para o corpo da função. Desta forma, quando passamos uma lista enorme como argumento, não haverá a cópia  de todos os seus itens para um novo local em memória. Não se esqueça que até mesmo números inteiros são objetos para o Python. 

Ao passar objetos mutáveis (p. ex: listas e dicionários) como parâmetro, eles podem ser alterados pela função que os chamou e as alterações são visíveis para a função chamadora. Já os objetos imutáveis (p. ex: inteiros e strings), não podem ser alterados pela função chamada, logo, a função chamadora pode ter certeza de que a função chamada não irá alterar os valores das variáveis.

## Exercícios

1. Faça um programa contendo o método `verifica(numero)` que retorne 1 se o número digitado for positivo ou 0 se for negativo.
"""

def verifica(numeroDigitado):
  if numeroDigitado >= 0:
    return "1"
  elif numeroDigitado < 0:
    return "0"
numeroDigitado = int(input("digite um nnumero: "))
print(verifica(numeroDigitado))

"""2. Faça um programa contendo o método `somar(inicio, fim)` que receba dois números inteiros positivos como parâmetro e retorne a soma dos N números inteiros existentes entre eles. Ou seja, os parâmetros são exclusives, ou seja, os valores de início e fim não aparecerão no resultado."""

def soma(inicio, fim)

"""3. Faça um programa contendo o método `divisores(a, b, c)` que receba três números inteiros a, b e c, sendo a maior que 1. A função deverá somar todos os inteiros entre b e c que sejam divisíveis por a (inclusive b e c) e retornar o resultado da soma para ser impresso."""



"""4. Faça um método `converte_horario(segundos)` que receba um único valor representando segundos e converta esse valor para horas, minutos e segundos; seguindo o formato 00:00:00."""



"""5. Crie o método `calcula_reajuste(preco_antigo, preco_atual)` que receba os valores antigo e atual de um produto e determine o percentual de acréscimo entre esses valores."""

def calcula_reajuste(preco_antigo, preco_atual):
  percent = ((precoAtual / precoAnt) * 100)
  percent = percent - 100 
  return percent

precoAnt = int(input("digite o preço antigo: "))
precoAtual = int(input("digite o preço atual: "))
print(calcula_reajuste(precoAnt, precoAtual))

"""6. Crie o método `imprime_multiplicacao(n)` que receba como parâmetro um número inteiro no intervalo de 1 a 9 (inclusive) e mostre a seguinte tabela de multiplicação (no exemplo, n = 9):


1<br/> 
2  4 <br/>
3 6 9  <br/>
4 8 12 16  <br/>
5 10 15 20 25  <br/>
6 12 18 24 30 36  <br/>
7 14 21 28 35 42 49  <br/>
8 16 24 32 40 48 56 64  <br/>
9 18 27 36 45 54 63 72 81  <br/>
"""



"""7. crie o método `media_alunos(nota1, nota2, nota3, tipo)` que receba as três notas de um aluno como parâmetros e um número inteiro indicando o tipo de média. Se o número for 0, a função deverá calcular a média aritmética das notas do aluno; se for 1, deverá calcular a média ponderada, com pesos os respectivos pesos: 5, 3 e 2. A média calculada deverá ser retornada pela função."""

def media_alunos(nota1, nota2, nota3, tipo):
  if tipo == "0":
    soma = nota1 + nota2 + nota3
    media = soma / 3
    return media
  elif tipo == "1":
    peso1 = 5
    peso2 = 3
    peso3 = 2
    mdp1 = (nota1 * peso1)
    mdp2 = (nota2 * peso2)
    mdp3 = (nota3 * peso3)
    mediaP = (mdp1 + mdp2 + mdp3) / (peso1 + peso2 + peso3)
    return mediaP
nota1 = int(input("digite sua nota 1: "))
nota2 = int(input("digite sua nota 2: "))
nota3 = int(input("digite sua nota 3: "))
tipo = input("digite um numero: 0 para aritmetica e 1 para ponderada: ")
print(media_alunos(nota1, nota2, nota3, tipo))

"""8. Faça o método `maior_menor(numeros)` que receba um vetor de números inteiros como parâmetro, em seguida, determine e imprima na tela o maior e o menor número."""

def maiorN(numeros):
  maiorNumero = -1
  for i in numeroN:
    if i > maiorNumero:
      maiorNumero = i
  return maiorNumero
def menorN(numeros):
  menorNumero = 15568
  for i in numeroN:
    if i < menorNumero:
      menorNumero = i
  return menorNumero
numeroN = [9, 8, 6, 3, 4, 101]
print(maiorN(numeroN))
print(menorN(numeroN))

"""9. Foi realizada uma pesquisa sobre algumas características físicas dos habitantes de uma região. Foram coletados os seguintes dados de cada habitante: sexo, cor dos olhos (A — azuis; ou C — castanhos), cor dos cabelos (L — louros; P — pretos; ou C — castanhos) e idade. Implemente os seguintes métodos:

    1. `leia_dados()`: leia esses dados, armazene e retorne os dados em uma lista;
    2. `media_idades(dados)`: calcula e retorne a média de idade das pessoas com olhos castanhos e cabelos pretos;
    3. `maior_idade(dados)`: determina e retorne a maior idade entre os habitantes;
    4. `frequencia_individuos(dados)`: calcula e retorna a quantidade de indivíduos do sexo feminino com idade entre 18 e 35 anos (inclusive) e que tenham olhos azuis e cabelos louros.
"""



"""10. Implemente o método `fatorial(n)` que receba como parâmetro um número inteiro e retorne o fatorial deste número."""

def fatorial(n):
  resultado = 1
  contador = 1

  while contador <= numero:
    resultado = resultado * contador
    contador = contador + 1
  return resultado  
numero = int(input("Fatorial de: ") )
print(fatorial(numero))

"""11. Faça o método `calcula_fatorial(numeros)` que receba uma lista de números inteiros como parâmetro. Ao final dessa função, deverá ter sido gerado um vetor `resultados_fatorial` contendo o fatorial de cada elemento da lista de números passada como parâmetro."""



"""12. Crie o método `identifica_numeros_pares(numeros)` que recebe um vetor de números inteiros como parâmetro, calcule e mostre na tela os números pares e suas respectivas posições."""

def identifica_numeros_pares(numeros):
  VetorPar = []
  for i in vetor:
    if (i % 2) == 0:
      npar = i  
      VetorPar.append(npar)
  return VetorPar
vetor = [1, 3, 4, 2, 9,5]
print(identifica_numeros_pares(vetor))

"""13. Crie o método `intercala(a, b)` que receba dois vetores númericos como parâmetro e retorne o vetor resultante da intercalação deles, por exemplo:

    * Vetor A = [3, 5, 4, 2, 2, 5, 3, 2, 5, 9]
    * Vetor B = [7, 15, 20, 0, 18, 4, 55, 23, 8, 6]
    * Vetor Intercalado = [3, 7, 5, 15, 4, 20, 2, 0, 2, 18, 5, 4, 3, 55, 2, 23, 5, 8, 9, 6]
"""



"""14. Implemente o método `uniao(a, b)` que receba dois vetores numéricos como parâmetro, calcule e retorne um vetor numérico com a união entre a e b (A ∪ B), ou seja, que possua todos os elementos dos vetores A e B, sem repetições."""



"""15. Implemente o método `diferenca(a, b)` que receba dois vetores numéricos como parâmetro, calcule e retorne um vetor numérico com a diferença entre a e b (A - B), ou seja, todos os elementos do vetores A que não existam no vetor B, sem repetições."""



"""16. Implemente o método `intersecao(a, b)` que receba dois vetores numéricos como parâmetro, calcule e retorne um vetor numérico com a intersecção entre a e b (A ∩ B), ou seja, contenha apenas os elementos que aparecem nos dois vetores, sem repetições."""



"""17. Implemente o método `par(n)` que receba como parâmetro um número e retorne verdadeiro (true) se ele for par ou falso (false) se ele for ímpar."""

def par(n):
  a = n % 2
  if a != 0:
    valor = "false"
  elif a == 0:
    valor = "true"
  return valor
print(par(2))

"""18. Implemente o método `max(numeros)` que receba como parâmetro uma lista de números e retorne o *maior número* encontrado na lista."""

def min(numeros):
  maiorNumero = 0
  for i in numeroN:
    if i > maiorNumero:
      maiorNumero = i
  return maiorNumero
numeroN = [9, 8, 6, 3, 4, 101]
print(min(numeroN))

"""19. Implemente o método `min(numeros)` que receba como parâmetro uma lista de números e retorne o *menor número* encontrado na lista."""

def min(numeros):
  menorNumero = 10000
  for i in numeroN:
    if i < menorNumero:
      menorNumero = i
  return menorNumero
numeroN = [9, 8, 6, 3, 4, 101]
print(min(numeroN))

"""20. Escreva o método `multiplo(a, b)` que receba dois números inteiros como parâmetro e retorne verdadeiro (true) se o primeiro for um múltiplo do segundo. Por exemplo: 

    * Se o usuário digitar 15 e 3, o primeiro número será múltiplo do segundo;
    * Se o usuário digitar 2 e 4, o primeiro número não será múltiplo do segundo. 

> **Dica:** use o operador módulo para obter o resto da divisão.
"""



"""21. Implemente o método `imprime_vetor(vetor, codigo)` que receba como parâmetro um vetor de itens que será impresso e um código indicando a ordem da impressão. Se o código for igual a 0, o vetor deverá ser impresso de maneira crescente, caso contrário, se o código for igual a 1 o vetor deverá ser impresso de maneira decrescente."""

def imprime_vetor(vetor, codigo):
  if codigo == 0:
    for i in numeros:
      numeros.sort()
  else:
    for i in numeros:
      numeros.sort(reverse=True)
  return numeros
numeros = [1,5,8,3,6,8] 
print(imprime_vetor(numeros, 1))

"""22. Implemente o método `primo(n)` que receba um número como parâmetro e retorna verdadeiro (true) se ele for primo, caso contrário, falso (false). 

> Um número é primo quando é divisível apenas por 1 e por ele mesmo
"""

def primo(n):
  nPrimo = numeroDigitado
  if numeroDigitado % 2 == 1:
    return "primo"
  else:
    return "não primo"
numeroDigitado = int(input("Digite um numero: "))
print(primo(numeroDigitado))

"""23. Crie o método `media(numeros)` que receba uma lista de números como parâmetro e retorno a média artimética."""

def media(numeros):
  soma = 0
  for i in numeros:
    soma = soma + i 
  quant = len(numeros)
  mediaA = soma / quant
  return media
numeros = [1, 3, 5, 9]
print(media(numeros))

"""24. Faça o método `analisa_numeros(numeros)` que receba uma lista de números como parâmetro, calcule e mostre:

    1. A Soma dos números;
    2. A quantidade de números;
    3. A média dos números;
    4. O maior número;
    5. O menor número;
    6. A média dos números pares;
    7. A porcentagem dos números ímpares entre todos os números da lista.

> Você pode utilizar métodos criados nos exercícios anteriores.
"""



"""25. Uma empresa quer transmitir dados pelo telefone, mas está preocupada com a interceptação telefônica. Todos os seus dados são transmitidos  como inteiros de quatro dígitos. Ela pediu para que você escreva um programa que criptografe seus dados, para que eles possam ser transmitidos com mais segurança. Implemente a função `criptogra(numero)` que receba como parâmetro um número inteiro de quatro dígitos e criptografe-o da seguinte forma: 

    * Substitua cada um dos dígitos do número usando a seguinte fórmula: `(digito +  7) módulo 10`; 
    * Após a substituição, troque o primeiro dígito pelo terceiro e troque o segundo dígito pelo quarto;
    * Retorne o número inteiro criptografado.
"""

